import { BmpDepth, ProcessedBmpData } from '../types/bmp';
import { rgbToVgaDac } from './palettes';

export interface QBasicCodeTemplates {
  loaderCode: string;
  saverCode: string;
  inlineDataCode: string;
  headerSpecText: string;
}

export function generateQBasicCode(
  bmpData: ProcessedBmpData,
  filename: string = 'IMAGE.BMP'
): QBasicCodeTemplates {
  const { width, height, depth, rowSize, paddingBytesPerRow, palette, indexedPixelGrid } = bmpData;

  const targetScreen =
    depth === 1 ? 'SCREEN 11 \' (640x480 Monochrome)' :
    depth === 4 ? (width <= 320 && height <= 200 ? 'SCREEN 7 \' (320x200 16-color)' : 'SCREEN 12 \' (640x480 16-color)') :
    'SCREEN 13 \' (320x200 256-color VGA)';

  // 1. GENERATE LOADER CODE (LOADBMP.BAS)
  const loaderCode = `' =========================================================================
' LOADBMP.BAS - Universal Windows BMP Loader for QBasic / QuickBASIC 4.5 / QB64
' Supports: 1-Bit (Mono), 4-Bit (16-color), 8-Bit (256-color), and 24-Bit BMPs
' Generated by QBasic BMP Studio
' File: ${filename}  |  Dimensions: ${width}x${height}  |  Depth: ${depth}-bit
' Row Size (padded to 4-byte boundary): ${rowSize} bytes (${paddingBytesPerRow} pad bytes)
' =========================================================================

DEFINT A-Z

' 14-byte BMP File Header
TYPE BitmapFileHeader
    bfType      AS INTEGER   ' Magic identifier: &H4D42 ("BM")
    bfSize      AS LONG      ' Total file size in bytes
    bfReserved1 AS INTEGER   ' Reserved (always 0)
    bfReserved2 AS INTEGER   ' Reserved (always 0)
    bfOffBits   AS LONG      ' Offset to start of pixel data
END TYPE

' 40-byte BMP Info Header (Windows DIB format)
TYPE BitmapInfoHeader
    biSize          AS LONG     ' Size of InfoHeader (40)
    biWidth         AS LONG     ' Bitmap width in pixels
    biHeight        AS LONG     ' Bitmap height in pixels (positive = bottom-up)
    biPlanes        AS INTEGER  ' Number of color planes (must be 1)
    biBitCount      AS INTEGER  ' Bits per pixel: 1, 4, 8, or 24
    biCompression   AS LONG     ' Compression type (0 = BI_RGB uncompressed)
    biSizeImage     AS LONG     ' Image data size including scanline padding
    biXPelsPerMeter AS LONG     ' Horizontal resolution (pixels/meter)
    biYPelsPerMeter AS LONG     ' Vertical resolution (pixels/meter)
    biClrUsed       AS LONG     ' Number of colors in palette table
    biClrImportant  AS LONG     ' Number of important colors (0 = all)
END TYPE

DIM fileHdr AS BitmapFileHeader
DIM infoHdr AS BitmapInfoHeader

DIM fileNum AS INTEGER
DIM bmpName AS STRING
bmpName$ = "${filename}"

fileNum% = FREEFILE
OPEN bmpName$ FOR BINARY AS #fileNum%

' Read and validate headers
GET #fileNum%, 1, fileHdr
IF fileHdr.bfType <> &H4D42 THEN
    PRINT "ERROR: File is not a valid Windows BMP (Missing 'BM' signature)!"
    CLOSE #fileNum%
    END
END IF

GET #fileNum%, 15, infoHdr
IF infoHdr.biSize <> 40 OR infoHdr.biCompression <> 0 THEN
    PRINT "ERROR: Unsupported BMP format. Only uncompressed Windows DIBs supported."
    CLOSE #fileNum%
    END
END IF

PRINT "Loading: "; bmpName$
PRINT "Resolution:"; infoHdr.biWidth; "x"; infoHdr.biHeight; "@"; infoHdr.biBitCount; "-bit"
PRINT "Pixel Data Offset:"; fileHdr.bfOffBits; "bytes"
SLEEP 1

' Select optimal QBasic graphics mode based on bit depth
SELECT CASE infoHdr.biBitCount
    CASE 1
        SCREEN 11 ' 640x480 2-color monochrome
    CASE 4
        IF infoHdr.biWidth <= 320 AND infoHdr.biHeight <= 200 THEN
            SCREEN 7 ' 320x200 16-color
        ELSE
            SCREEN 12 ' 640x480 16-color
        END IF
    CASE 8, 24
        SCREEN 13 ' 320x200 256-color Mode 13h
    CASE ELSE
        PRINT "Unsupported bit depth:"; infoHdr.biBitCount
        CLOSE #fileNum%
        END
END SELECT

' Load and set VGA DAC Palette for indexed modes (1-bit, 4-bit, 8-bit)
IF infoHdr.biBitCount <= 8 THEN
    DIM numColors AS LONG
    numColors& = infoHdr.biClrUsed
    IF numColors& = 0 THEN numColors& = 2 ^ infoHdr.biBitCount

    ' Seek to palette start: Byte 55 (14 + 40 + 1)
    SEEK #fileNum%, 55
    DIM b AS STRING * 1, g AS STRING * 1, r AS STRING * 1, res AS STRING * 1

    FOR i% = 0 TO numColors& - 1
        GET #fileNum%, , b
        GET #fileNum%, , g
        GET #fileNum%, , r
        GET #fileNum%, , res

        ' Convert BMP 0..255 color range to QBasic VGA DAC 0..63 scale
        redDAC% = ASC(r) \\ 4
        grnDAC% = ASC(g) \\ 4
        bluDAC% = ASC(b) \\ 4

        ' Program VGA Hardware Palette Registers (Ports &H3C8 and &H3C9)
        OUT &H3C8, i%
        OUT &H3C9, redDAC%
        OUT &H3C9, grnDAC%
        OUT &H3C9, bluDAC%
    NEXT i%
END IF

' Calculate scanline byte width padded to 4-byte (32-bit) boundary
DIM rowBytes AS LONG
rowBytes& = INT((infoHdr.biWidth * infoHdr.biBitCount + 31) / 32) * 4

' Position file pointer directly at pixel data start
SEEK #fileNum%, fileHdr.bfOffBits + 1

' BMP rows are stored BOTTOM-TO-TOP: Row 0 is at the bottom of the screen!
DIM rawRow AS STRING
rawRow$ = SPACE$(rowBytes&)

${depth === 8 ? `' Fast VGA direct video memory blitter setup for SCREEN 13 (A000:0000)
DEF SEG = &HA000
` : ''}
FOR y% = infoHdr.biHeight - 1 TO 0 STEP -1
    GET #fileNum%, , rawRow$

${depth === 1 ? `    ' Unpack 1-bit pixels (8 pixels packed per byte, MSB first)
    byteIdx% = 1
    FOR x% = 0 TO infoHdr.biWidth - 1 STEP 8
        curByte% = ASC(MID$(rawRow$, byteIdx%, 1))
        byteIdx% = byteIdx% + 1
        FOR bit% = 7 TO 0 STEP -1
            px% = x% + (7 - bit%)
            IF px% < infoHdr.biWidth THEN
                col% = (curByte% AND (2 ^ bit%)) \\ (2 ^ bit%)
                PSET (px%, y%), col%
            END IF
        NEXT bit%
    NEXT x%` : depth === 4 ? `    ' Unpack 4-bit pixels (2 pixels packed per byte, high nibble first)
    byteIdx% = 1
    FOR x% = 0 TO infoHdr.biWidth - 1 STEP 2
        curByte% = ASC(MID$(rawRow$, byteIdx%, 1))
        byteIdx% = byteIdx% + 1
        c1% = (curByte% AND &HF0) \\ 16
        c2% = (curByte% AND &H0F)
        PSET (x%, y%), c1%
        IF x% + 1 < infoHdr.biWidth THEN PSET (x% + 1, y%), c2%
    NEXT x%` : depth === 8 ? `    ' 8-bit pixels (1 byte per pixel) - direct VGA memory copy
    vgaOffset& = y% * 320&
    FOR x% = 0 TO infoHdr.biWidth - 1
        IF x% < 320 AND y% < 200 THEN
            col% = ASC(MID$(rawRow$, x% + 1, 1))
            POKE vgaOffset& + x%, col%
        END IF
    NEXT x%` : `    ' 24-bit TrueColor pixels (3 bytes BGR per pixel)
    bIdx% = 1
    FOR x% = 0 TO infoHdr.biWidth - 1
        blu% = ASC(MID$(rawRow$, bIdx%, 1))
        grn% = ASC(MID$(rawRow$, bIdx% + 1, 1))
        red% = ASC(MID$(rawRow$, bIdx% + 2, 1))
        bIdx% = bIdx% + 3
        ' In standard QBasic SCREEN 13, approximate nearest color or draw gray:
        gray% = INT(red% * .3 + grn% * .59 + blu% * .11) \\ 16
        PSET (x%, y%), 16 + gray%
    NEXT x%`}
NEXT y%

${depth === 8 ? 'DEF SEG \' Restore default BASIC data segment' : ''}
CLOSE #fileNum%

' Wait for keypress then restore screen
DO: LOOP UNTIL INKEY$ <> ""
SCREEN 0: WIDTH 80
END
`;

  // 2. GENERATE SCREEN-TO-BMP SAVER CODE (SAVEBMP.BAS)
  const saverCode = `' =========================================================================
' SAVEBMP.BAS - Save Current QBasic Screen to standard Windows BMP
' Supports saving SCREEN 11 (1-bit), SCREEN 12 (4-bit), and SCREEN 13 (8-bit)
' Generated by QBasic BMP Studio
' =========================================================================

DEFINT A-Z

DECLARE SUB SaveBMP (filename$, scrWidth%, scrHeight%, bitDepth%)

' Example demo: Draw something to screen then save
${targetScreen}
CLS

' Draw sample pattern
FOR r% = 1 TO 80 STEP 3
    CIRCLE (${Math.floor(width / 2)}, ${Math.floor(height / 2)}), r%, (r% MOD ${depth === 1 ? 2 : depth === 4 ? 15 + 1 : 255})
NEXT r%
LINE (0, 0)-(${width - 1}, ${height - 1}), 15, B

LOCATE 1, 1: PRINT "Saving to ${filename}...";
CALL SaveBMP("${filename}", ${width}, ${height}, ${depth})
LOCATE 1, 1: PRINT "Saved successfully! Press any key.";

DO: LOOP UNTIL INKEY$ <> ""
SCREEN 0: WIDTH 80
END

' -------------------------------------------------------------------------
' Subroutine: SaveBMP
' Captures active QBasic screen and writes a compliant Windows BMP file
' -------------------------------------------------------------------------
SUB SaveBMP (filename$, scrWidth%, scrHeight%, bitDepth%)
    DIM fileNum AS INTEGER
    DIM numColors AS LONG
    DIM paletteSize AS LONG
    DIM rowBytes AS LONG
    DIM rawSize AS LONG
    DIM totalSize AS LONG
    DIM dataOffset AS LONG

    SELECT CASE bitDepth%
        CASE 1: numColors& = 2
        CASE 4: numColors& = 16
        CASE 8: numColors& = 256
        CASE ELSE: numColors& = 0
    END SELECT

    paletteSize& = numColors& * 4
    rowBytes& = INT((scrWidth% * bitDepth% + 31) / 32) * 4
    rawSize& = rowBytes& * scrHeight%
    dataOffset& = 14 + 40 + paletteSize&
    totalSize& = dataOffset& + rawSize&

    fileNum% = FREEFILE
    OPEN filename$ FOR BINARY AS #fileNum%

    ' 1. Write BITMAPFILEHEADER (14 bytes)
    PUT #fileNum%, 1, MKI$(&H4D42)           ' bfType = "BM"
    PUT #fileNum%, 3, MKL$(totalSize&)       ' bfSize
    PUT #fileNum%, 7, MKI$(0)                ' bfReserved1
    PUT #fileNum%, 9, MKI$(0)                ' bfReserved2
    PUT #fileNum%, 11, MKL$(dataOffset&)     ' bfOffBits

    ' 2. Write BITMAPINFOHEADER (40 bytes)
    PUT #fileNum%, 15, MKL$(40)              ' biSize
    PUT #fileNum%, 19, MKL$(scrWidth%)       ' biWidth
    PUT #fileNum%, 23, MKL$(scrHeight%)      ' biHeight (positive = bottom-up)
    PUT #fileNum%, 27, MKI$(1)               ' biPlanes
    PUT #fileNum%, 29, MKI$(bitDepth%)       ' biBitCount
    PUT #fileNum%, 31, MKL$(0)               ' biCompression (BI_RGB)
    PUT #fileNum%, 35, MKL$(rawSize&)        ' biSizeImage
    PUT #fileNum%, 39, MKL$(2835)            ' biXPelsPerMeter (72 DPI)
    PUT #fileNum%, 43, MKL$(2835)            ' biYPelsPerMeter
    PUT #fileNum%, 47, MKL$(numColors&)      ' biClrUsed
    PUT #fileNum%, 51, MKL$(0)               ' biClrImportant

    ' 3. Read Hardware DAC and Write Color Palette (RGBQUAD: B, G, R, 0)
    SEEK #fileNum%, 55
    FOR c% = 0 TO numColors& - 1
        ' Read 6-bit DAC registers from VGA port &H3C7 / &H3C9
        OUT &H3C7, c%
        r6% = INP(&H3C9)
        g6% = INP(&H3C9)
        b6% = INP(&H3C9)

        ' Scale 0..63 DAC to 0..255 BMP standard
        r255% = r6% * 4
        g255% = g6% * 4
        b255% = b6% * 4

        PUT #fileNum%, , CHR$(b255%)
        PUT #fileNum%, , CHR$(g255%)
        PUT #fileNum%, , CHR$(r255%)
        PUT #fileNum%, , CHR$(0)
    NEXT c%

    ' 4. Stream Screen Rows (Bottom-to-Top with 4-byte padding)
    SEEK #fileNum%, dataOffset& + 1
    DIM padBytes AS INTEGER
    DIM padStr AS STRING

    IF bitDepth% = 1 THEN
        unpaddedBytes% = (scrWidth% + 7) \\ 8
    ELSEIF bitDepth% = 4 THEN
        unpaddedBytes% = (scrWidth% + 1) \\ 2
    ELSEIF bitDepth% = 8 THEN
        unpaddedBytes% = scrWidth%
    END IF
    padBytes% = rowBytes& - unpaddedBytes%
    IF padBytes% > 0 THEN padStr$ = STRING$(padBytes%, 0)

    FOR y% = scrHeight% - 1 TO 0 STEP -1
        rowStr$ = ""
        IF bitDepth% = 1 THEN
            curByte% = 0
            bitPos% = 7
            FOR x% = 0 TO scrWidth% - 1
                col% = POINT(x%, y%) AND 1
                curByte% = curByte% OR (col% * (2 ^ bitPos%))
                bitPos% = bitPos% - 1
                IF bitPos% < 0 THEN
                    rowStr$ = rowStr$ + CHR$(curByte%)
                    curByte% = 0
                    bitPos% = 7
                END IF
            NEXT x%
            IF bitPos% <> 7 THEN rowStr$ = rowStr$ + CHR$(curByte%)
        ELSEIF bitDepth% = 4 THEN
            curByte% = 0
            isHigh% = 1
            FOR x% = 0 TO scrWidth% - 1
                col% = POINT(x%, y%) AND &H0F
                IF isHigh% = 1 THEN
                    curByte% = col% * 16
                    isHigh% = 0
                ELSE
                    curByte% = curByte% OR col%
                    rowStr$ = rowStr$ + CHR$(curByte%)
                    curByte% = 0
                    isHigh% = 1
                END IF
            NEXT x%
            IF isHigh% = 0 THEN rowStr$ = rowStr$ + CHR$(curByte%)
        ELSEIF bitDepth% = 8 THEN
            FOR x% = 0 TO scrWidth% - 1
                rowStr$ = rowStr$ + CHR$(POINT(x%, y%) AND 255)
            NEXT x%
        END IF

        PUT #fileNum%, , rowStr$
        IF padBytes% > 0 THEN PUT #fileNum%, , padStr$
    NEXT y%

    CLOSE #fileNum%
END SUB
`;

  // 3. GENERATE INLINE DATA STATEMENTS (RUNNABLE WITHOUT EXTERNAL FILE)
  // For quick standalone QBasic demo! Limit to reasonable sprite size or sample
  const sampleW = Math.min(width, 160);
  const sampleH = Math.min(height, 100);

  // Generate palette DATA statements
  let paletteDataLines = '';
  if (depth <= 8 && palette.length > 0) {
    const palCount = Math.min(palette.length, depth === 1 ? 2 : depth === 4 ? 16 : 64);
    const palItems: string[] = [];
    for (let i = 0; i < palCount; i++) {
      const q = palette[i];
      const [r6, g6, b6] = rgbToVgaDac(q.rgbRed, q.rgbGreen, q.rgbBlue);
      palItems.push(`${r6},${g6},${b6}`);
    }
    // Chunk into lines
    for (let i = 0; i < palItems.length; i += 8) {
      paletteDataLines += `DATA ${palItems.slice(i, i + 8).join(', ')}\n`;
    }
  }

  // Generate pixel DATA lines (run-length or chunked numbers)
  let pixelDataLines = '';
  const flatPixels: number[] = [];
  for (let y = 0; y < sampleH; y++) {
    for (let x = 0; x < sampleW; x++) {
      flatPixels.push(indexedPixelGrid[y][x]);
    }
  }

  // Group into compact comma-separated lines of 20 numbers
  for (let i = 0; i < flatPixels.length; i += 20) {
    pixelDataLines += `DATA ${flatPixels.slice(i, i + 20).join(',')}\n`;
    if (i > 3000) {
      pixelDataLines += `' ... (truncated for brevity; see full BMP file download) ...\n`;
      break;
    }
  }

  const inlineDataCode = `' =========================================================================
' INLINEDAT.BAS - Standalone QBasic Code with Embedded Image Data
' No external files required! Ready to run in QBasic 1.1 / QB64 / DOSBox.
' Dimensions: ${sampleW}x${sampleH}  |  Palette Colors: ${depth === 1 ? 2 : depth === 4 ? 16 : Math.min(palette.length, 64)}
' =========================================================================

DEFINT A-Z

${targetScreen}
CLS

' 1. Set Custom Palette from DATA statements
${paletteDataLines ? `' Read DAC colors (0..63)
RESTORE PaletteData
FOR i% = 0 TO ${depth === 1 ? 1 : depth === 4 ? 15 : Math.min(palette.length - 1, 63)}
    READ r%, g%, b%
    OUT &H3C8, i%
    OUT &H3C9, r%
    OUT &H3C9, g%
    OUT &H3C9, b%
NEXT i%` : ''}

' 2. Draw Image Pixels onto screen
RESTORE PixelData
FOR y% = 0 TO ${sampleH - 1}
    FOR x% = 0 TO ${sampleW - 1}
        READ c%
        PSET (x%, y%), c%
    NEXT x%
NEXT y%

LOCATE 24, 1: PRINT "Embedded render complete. Press any key.";
DO: LOOP UNTIL INKEY$ <> ""
SCREEN 0: WIDTH 80
END

${paletteDataLines ? `PaletteData:
${paletteDataLines}` : ''}
PixelData:
${pixelDataLines}
`;

  // 4. HEADER SPECIFICATION REFERENCE TEXT
  const headerSpecText = `================================================================================
MICROSOFT WINDOWS DIB BITMAP (.BMP) FILE SPECIFICATION & QBASIC MAPPING
================================================================================

1. BITMAPFILEHEADER (14 BYTES)
--------------------------------------------------------------------------------
Offset (Dec) | Size | Name        | Value in File  | QBasic Type | Description
-------------+------+-------------+----------------+-------------+-----------------------------
0x00 (0)     | 2    | bfType      | 0x4D42 ("BM")  | INTEGER     | Windows DIB signature ('B', 'M')
0x02 (2)     | 4    | bfSize      | ${bmpData.fileHeader.bfSize.toString().padEnd(14)} | LONG        | Total file size in bytes
0x06 (6)     | 2    | bfReserved1 | 0              | INTEGER     | Reserved (must be 0)
0x08 (8)     | 2    | bfReserved2 | 0              | INTEGER     | Reserved (must be 0)
0x0A (10)    | 4    | bfOffBits   | ${bmpData.fileHeader.bfOffBits.toString().padEnd(14)} | LONG        | Byte offset where pixel data begins

2. BITMAPINFOHEADER (40 BYTES)
--------------------------------------------------------------------------------
Offset (Dec) | Size | Name        | Value in File  | QBasic Type | Description
-------------+------+-------------+----------------+-------------+-----------------------------
0x0E (14)    | 4    | biSize      | 40 (0x28)      | LONG        | Size of this header structure
0x12 (18)    | 4    | biWidth     | ${width.toString().padEnd(14)} | LONG        | Width of image in pixels
0x16 (22)    | 4    | biHeight    | ${height.toString().padEnd(14)} | LONG        | Height (Positive = Bottom-Up scanlines!)
0x1A (26)    | 2    | biPlanes    | 1              | INTEGER     | Number of color planes (must be 1)
0x1C (28)    | 2    | biBitCount  | ${depth.toString().padEnd(14)} | INTEGER     | Bits per pixel (1, 4, 8, or 24)
0x1E (30)    | 4    | biCompress  | 0 (BI_RGB)     | LONG        | Compression (0 = uncompressed raw)
0x22 (34)    | 4    | biSizeImage | ${bmpData.infoHeader.biSizeImage.toString().padEnd(14)} | LONG        | Image data size with row padding
0x26 (38)    | 4    | biXPels/M   | 2835           | LONG        | Horizontal resolution (~72 DPI)
0x2A (42)    | 4    | biYPels/M   | 2835           | LONG        | Vertical resolution (~72 DPI)
0x2E (46)    | 4    | biClrUsed   | ${bmpData.infoHeader.biClrUsed.toString().padEnd(14)} | LONG        | Colors in palette (${depth === 24 ? '0 for 24-bit' : depth === 8 ? '256' : depth === 4 ? '16' : '2'})
0x32 (50)    | 4    | biClrImp    | 0              | LONG        | Important colors (0 = all)

3. COLOR PALETTE TABLE (RGBQUAD ARRAY)
--------------------------------------------------------------------------------
Offset: Byte 54 (0x36)
Structure of each RGBQUAD (4 bytes):
  Byte 0: Blue  (0-255)
  Byte 1: Green (0-255)
  Byte 2: Red   (0-255)
  Byte 3: Reserved (0)

Total Palette Size:
  1-bit:  2 colors  * 4 bytes = 8 bytes    (Offsets 54 - 61)
  4-bit: 16 colors  * 4 bytes = 64 bytes   (Offsets 54 - 117)
  8-bit: 256 colors * 4 bytes = 1024 bytes (Offsets 54 - 1077)
 24-bit: No palette table (pixel data starts immediately at offset 54)

IMPORTANT QBASIC HARDWARE NOTE (VGA DAC CONVERSION):
  BMP palettes store color channels in standard 0-255 range.
  The IBM VGA DAC controller hardware (ports &H3C8 and &H3C9) only accepts
  6 bits per channel (0 to 63)!
  To convert in QBasic:
    OUT &H3C8, paletteIndex%
    OUT &H3C9, redChannel% \\ 4
    OUT &H3C9, greenChannel% \\ 4
    OUT &H3C9, blueChannel% \\ 4

4. SCANLINE 4-BYTE (32-BIT) PADDING FORMULA
--------------------------------------------------------------------------------
Windows requires every scanline row in pixel data to be aligned on a 4-byte boundary:
  RowBytes = INT((biWidth * biBitCount + 31) / 32) * 4

In this file:
  Width: ${width} pixels
  Bit Depth: ${depth} bits
  Raw row bits: ${width * depth} bits -> ${Math.ceil((width * depth) / 8)} bytes
  Padded row bytes: ${rowSize} bytes
  Padding per row: ${paddingBytesPerRow} zero-bytes added at the end of each scanline!

5. BOTTOM-TO-TOP ROW ORDER (THE "UPSIDE-DOWN" BMP QUIRK)
--------------------------------------------------------------------------------
If biHeight is positive (${height}), the first row stored in the file is the
BOTTOM scanline of the picture (Y = ${height - 1}). The last row stored in the
file is the TOP scanline (Y = 0).
To read correctly in QBasic:
  FOR y% = infoHdr.biHeight - 1 TO 0 STEP -1
      ' Read row and plot
  NEXT y%
`;

  return {
    loaderCode,
    saverCode,
    inlineDataCode,
    headerSpecText,
  };
}
